### ISSUE TITLE
Error with latest build from Actions tab

### ISSUE THREAD

**Issue by W1CK3DWORKS** [jpenilla/TabTPS#120]
**Describe the bug**
I am unsure as i am not the developer

**To Reproduce**
1. Start up server with latest build from actions 469
2. Execute `tabtps`
3. See error

**Expected behavior**
It should not happen

**Screenshots**
```
> tabtps                                                                                                                                                                                                  [11/8277]
[14:10:20 INFO]: An internal error occurred while attempting to perform this command.
[14:10:20 ERROR]: [TabTPS] An unhandled exception was thrown during command execution
java.lang.ClassCastException: class xyz.jpenilla.tabtps.spigot.command.BukkitConsoleCommander cannot be cast to class xyz.jpenilla.tabtps.common.User (xyz.jpenilla.tabtps.spigot.command.BukkitConsoleCommander an
d xyz.jpenilla.tabtps.common.User are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @125145cc)
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.permission.PredicatePermission$1.testPermission(PredicatePermission.java:64) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandManager.testPermission(CommandManager.java:395) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandManager.testPermission(CommandManager.java:398) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.determinePermissionResult(CommandTree.java:1004) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.parseCommand(CommandTree.java:226) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.lambda$parseCommand$2(CommandTree.java:295) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl$NonSchedulingExecutor.execute(ExecutionCoordinatorImpl.java:53) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2252) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.lambda$parseCommand$3(CommandTree.java:288) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2241) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.parseCommand(CommandTree.java:270) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.parseDirect(CommandTree.java:196) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.lambda$parse$0(CommandTree.java:177) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl$NonSchedulingExecutor.execute(ExecutionCoordinatorImpl.java:53) ~[?:?]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714) ~[?:?]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1937) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.util.CompletableFutures.scheduleOn(CompletableFutures.java:70) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.CommandTree.parse(CommandTree.java:177) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl.coordinateExecution(ExecutionCoordinatorImpl.java:98) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:91) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:65) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.CommandExecutor.executeCommand(CommandExecutor.java:63) ~[?:?]
        at xyz.jpenilla.tabtps.lib.org.incendo.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:120) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[paper-1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[paper-1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648) ~[paper-1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463) ~[paper-1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[paper-1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[paper-1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[paper-1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:829) [?:?]
> version tabtps
[14:10:23 INFO]: TabTPS version 1.3.23-SNAPSHOT+3f8b902
[14:10:23 INFO]: Monitor your server's performance in real time
[14:10:23 INFO]: Website: https://github.com/jpenilla/TabTPS
[14:10:23 INFO]: Author: jmp
> ver
[14:10:26 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:10:26 INFO]: Checking version, please wait...
```

**Server Software and Version:**
 - Vendor: Paper
 - Minecraft Version: 1.12.2
 - Output of /version command: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Additional context**
/

**Comment by W1CK3DWORKS** [comment]
works now!
