### ISSUE TITLE
I try to use Tabtps in a VPS server but failed

### ISSUE THREAD

**Issue by ProBeekeeper** [jpenilla/TabTPS#136]
![image](https://github.com/jpenilla/TabTPS/assets/111445232/62821ba9-9e95-457b-9761-5c5196a464ca)

java.lang.ClassCastException: class java.lang.Long cannot be cast to class [J (java.lang.Long and [J are in module java.base of loader 'bootstrap')
    at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.averageTickTime(SpigotReflection.java:118)
    at xyz.jpenilla.tabtps.spigot.service.SpigotTickTimeService.averageMspt(SpigotTickTimeService.java:34)
    at xyz.jpenilla.tabtps.common.module.MSPTModule.display(MSPTModule.java:48)
    at xyz.jpenilla.tabtps.common.module.ModuleRenderer.lambda$standardRenderFunction$0(ModuleRenderer.java:54)
    at xyz.jpenilla.tabtps.common.module.ModuleRenderer.render(ModuleRenderer.java:73)
    at xyz.jpenilla.tabtps.common.command.commands.TickInfoCommand$DefaultFormatter.formatTickTimes(TickInfoCommand.java:165)
    at xyz.jpenilla.tabtps.common.command.commands.TickInfoCommand.executeTickInfo(TickInfoCommand.java:101)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:91)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl$NonSchedulingExecutor.execute(ExecutionCoordinatorImpl.java:53)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1184)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2352)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.ExecutionCoordinatorImpl.coordinateExecution(ExecutionCoordinatorImpl.java:104)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:91)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:65)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.execution.CommandExecutor.executeCommand(CommandExecutor.java:63)
    at xyz.jpenilla.tabtps.lib.org.incendo.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:111)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
    at org.bukkit.craftbukkit.v1_20_R4.CraftServer.dispatchCommand(CraftServer.java:910)
    at org.bukkit.craftbukkit.v1_20_R4.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
    at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13)
    at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8)
    at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8)
    at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107)
    at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:416)
    at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:338)
    at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:325)
    at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1824)
    at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1800)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1242)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
    at net.minecraft.util.thread.IAsyncTaskHandler.A(SourceFile:136)
    at net.minecraft.server.MinecraftServer.bu(MinecraftServer.java:1221)
    at net.minecraft.server.MinecraftServer.A(MinecraftServer.java:1214)
    at net.minecraft.util.thread.IAsyncTaskHandler.bA(SourceFile:121)
    at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1185)
    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
    at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by jpenilla** [comment]
You need to include information like the server type and version, and plugin version. This is solved by sharing entire logs (https://mclo.gs) rather than snippets. I have a feeling this would be resolved by using Paper instead of Spigot, though.

**Comment by TheFattestCatProg** [comment]
I have problem with executing `tps` command on Spigot1.21, but other error. I think TabTPS is broken on spigot
![изображение](https://github.com/jpenilla/TabTPS/assets/80482083/10cd588d-5bf7-4d64-aca1-1e33790dc489)
