### ISSUE TITLE
I have a problem entering /ping on the server from the client side

### ISSUE THREAD

**Issue by Xray1716** [jpenilla/TabTPS#140]
`[14:03:03] [Server thread/WARN] [xyz.jpenilla.tabtps.spigot.TabTPSPlugin]: An unexpected error occurred during command execution

java.lang.NoClassDefFoundError: Could not initialize class xyz.jpenilla.tabtps.spigot.util.SpigotReflection$Holder

at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.spigotReflection(SpigotReflection.java:47) ~[?:?]

at xyz.jpenilla.tabtps.spigot.BukkitUser.ping(BukkitUser.java:75) ~[?:?]

at xyz.jpenilla.tabtps.common.util.PingUtil.coloredPing(PingUtil.java:38) ~[?:?]

at xyz.jpenilla.tabtps.common.command.commands.PingCommand.onPingSelf(PingCommand.java:125) ~[?:?]

at xyz.jpenilla.tabtps.lib.cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[?:?]

at xyz.jpenilla.tabtps.lib.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[?:?]

at xyz.jpenilla.tabtps.lib.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:189) ~[?:?]

at xyz.jpenilla.tabtps.lib.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[?:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[SimpleCommandMap.class:1.12.2-cb2fb32]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[CraftServer.class:1.12.2-cb2fb32]

at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1605) ~[pa.class:?]

at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1453) ~[pa.class:?]

at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) ~[la.class:?]

at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) ~[la.class:?]

at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]

at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:836) ~[MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) ~[MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:647) ~[MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

`
what is it and what is it eaten with?

**Comment by jpenilla** [comment]
Old versions of TabTPS are not supported, additionally you need to fill out the issue template properly.
