### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Micro-NaCl** [jpenilla/TabTPS#36]
Version 1.3.12 crashes on launch with Fabric Loader 0.14.0 & 0.14.3 (only tested these 2, works fine with 0.13.3). Tested with only TabTPS & fabric API.

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adventure-platform-fabric'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:156)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:69)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adventure-platform-fabric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.<clinit>(AdventurePrelaunch.java:48)
	... 10 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.<clinit>(AdventurePrelaunch.java:45)
	... 10 more

**Comment by jpenilla** [comment]
loader 0.14 is still beta, either use the [snapshot](https://jenkins.jpenilla.xyz/job/TabTPS/) of tabtps which is compatible, or downgrade loader to a stable release version
