### ISSUE TITLE
Crash on start on newer fabric loader version

### ISSUE THREAD

**Issue by CheatCod** [jpenilla/TabTPS#37]
**Describe the bug**
TabTPS crash on start on newer fabric loader version (0.14.3)

**To Reproduce**
1. Download fabric loader 0.14.3
2. Add fabric API and the mod
3. Start
4.Server crashes

**Expected behavior**
Server should start up without errors

**Screenshots**
```
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.3.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.3.jar:?]
    at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [server.jar:0.10.2]
 Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adventure-platform-fabric'!
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.3.jar:?]
    ... 8 more
 Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.3.jar:?]
    ... 8 more
 Caused by: java.lang.RuntimeException: Failed to load Classloader fields
    at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.<clinit>(AdventurePrelaunch.java:48) ~[adventure-platform-fabric-5.2.0-bd53f508382af52e.jar:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.3.jar:?]
    ... 8 more
 Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
    at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
    at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.<clinit>(AdventurePrelaunch.java:45) ~[adventure-platform-fabric-5.2.0-bd53f508382af52e.jar:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.3.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.3.jar:?]
    ... 8 more
```

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.2

**Additional context**

**Comment by jpenilla** [comment]
https://github.com/jpenilla/TabTPS/issues/36
