### ISSUE TITLE
Trying to run commands from client, unable to

### ISSUE THREAD

**Issue by ERBEpic** [jpenilla/TabTPS#50]
**Describe the bug**
All commands excluding /ping and /tabtps toggle _ result in an error

**To Reproduce**
1. Create a server with tabtps
2. Run a command that is not /ping or /tabtps toggle _

**Expected behavior**
For the commands to work

Here are the logs from the server after running /tabtps help, and /pingall respectively

[21:53:19] [Server thread/WARN]: An unexpected error occurred during command execution
java.lang.NoSuchFieldError: field_11735
	at net.kyori.adventure.platform.fabric.impl.server.ServerPlayerAudience.sendMessage(ServerPlayerAudience.java:93) ~[adventure-platform-fabric-5.4.0-SNAPSHOT-fc511e30baff9444.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at cloud.commandframework.minecraft.extras.MinecraftHelp.printIndexHelpTopic(MinecraftHelp.java:425) ~[cloud_commandframework_cloud-min.0-SNAPSHOT-6db0cbdba4996dec.jar:?]
	at cloud.commandframework.minecraft.extras.MinecraftHelp.printTopic(MinecraftHelp.java:340) ~[cloud_commandframework_cloud-min.0-SNAPSHOT-6db0cbdba4996dec.jar:?]
	at cloud.commandframework.minecraft.extras.MinecraftHelp.queryCommands(MinecraftHelp.java:325) ~[cloud_commandframework_cloud-min.0-SNAPSHOT-6db0cbdba4996dec.jar:?]
	at xyz.jpenilla.tabtps.common.command.commands.HelpCommand.executeHelp(HelpCommand.java:67) ~[tabtps-fabric-mc1.19.2-1.3.15.jar:?]
	at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:188) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.fabric.FabricExecutor.run(FabricExecutor.java:82) ~[cloud-1.8.0-SNAPSHOT-26448efdcdab2db6.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45010(class_3244.java:1339) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1320) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5386(class_1255.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zci000$modifiedRunLoop(MinecraftServer.java:3394) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

[21:53:39] [Server thread/WARN]: An unexpected error occurred during command execution
java.lang.NoSuchFieldError: field_11735
	at net.kyori.adventure.platform.fabric.impl.server.ServerPlayerAudience.sendMessage(ServerPlayerAudience.java:93) ~[adventure-platform-fabric-5.4.0-SNAPSHOT-fc511e30baff9444.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.ForwardingAudience$Single.sendMessage(ForwardingAudience.java:246) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[net_kyori_adventure-api-4.11.0-aa6ee877a601f97b.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at xyz.jpenilla.tabtps.common.command.commands.PingCommand.pingMultiple(PingCommand.java:205) ~[tabtps-fabric-mc1.19.2-1.3.15.jar:?]
	at xyz.jpenilla.tabtps.common.command.commands.PingCommand.onPingAll(PingCommand.java:106) ~[tabtps-fabric-mc1.19.2-1.3.15.jar:?]
	at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:188) ~[cloud_commandframework_cloud-cor.0-SNAPSHOT-774a62892ce1343e.jar:?]
	at cloud.commandframework.fabric.FabricExecutor.run(FabricExecutor.java:82) ~[cloud-1.8.0-SNAPSHOT-26448efdcdab2db6.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45010(class_3244.java:1339) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1320) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5386(class_1255.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zci000$modifiedRunLoop(MinecraftServer.java:3394) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by jpenilla** [comment]
Need the full log (use a paste site like https://paste.gg/), but it looks like you're probably using the wrong build for the version of Minecraft you're running.

**Comment by ERBEpic** [comment]
Heres a full log from server start to close, hope this helps
https://paste.gg/p/anonymous/caeb4f7f16ef4f1581f74e8489b1b774

**Comment by jpenilla** [comment]
Try the latest [snapshot](https://jenkins.jpenilla.xyz/job/TabTPS/lastSuccessfulBuild/), also it looks like you need to update geyser/floodgate

**Comment by ERBEpic** [comment]
Works perfectly now also updated geyser and floodgate. Thank you so much

**Comment by Splarkszter** [comment]
> Try the latest [snapshot](https://jenkins.jpenilla.xyz/job/TabTPS/lastSuccessfulBuild/).

1.19.1 Linux

Thanks that solved it for me.

**Comment by ERBEpic** [comment]
Trying the latest snapshot worked for me, using the link jpenilla sent above.

**Comment by alsoGAMER** [comment]
My bad, didn't saw that, it's working fine now.

**Comment by jpenilla** [comment]
Been meaning to do a release but haven't had the time yet

**Comment by jpenilla** [comment]
This is fixed in 1.3.16 for 1.19.3

**Comment by Altirix** [comment]
might be worth removing the broken version from modrinth and i assume curseforge, maybe replace it with the working snapshot? if not the original reply refers to the build https://jenkins.jpenilla.xyz/job/TabTPS/176/ as the link supplied has changed since its no longer the last successful build.
