### ISSUE TITLE
Plugin commands and display not working on spigot 1.19.2

### ISSUE THREAD

**Issue by ForgedCore8** [jpenilla/TabTPS#53]
When Starting the spigot server, I am met with this:

`[12:20:57] [Server thread/INFO]: [TabTPS] Enabling TabTPS v1.3.15
[12:20:57] [Server thread/WARN]: [TabTPS] ====================================================
[12:20:57] [Server thread/WARN]: [TabTPS]  TabTPS works better if you use Paper
[12:20:57] [Server thread/WARN]: [TabTPS]  as your server software.
[12:20:57] [Server thread/WARN]: [TabTPS]
[12:20:57] [Server thread/WARN]: [TabTPS]  Paper offers significant performance improvements,
[12:20:57] [Server thread/WARN]: [TabTPS]  bug fixes, security enhancements and optional
[12:20:57] [Server thread/WARN]: [TabTPS]  features for server owners to enhance their server.
[12:20:57] [Server thread/WARN]: [TabTPS]
[12:20:57] [Server thread/WARN]: [TabTPS]  Paper includes Timings v2, which is significantly
[12:20:57] [Server thread/WARN]: [TabTPS]  better at diagnosing lag problems over v1.
[12:20:57] [Server thread/WARN]: [TabTPS]
[12:20:57] [Server thread/WARN]: [TabTPS]  All of your plugins should still work, and the
[12:20:57] [Server thread/WARN]: [TabTPS]  Paper community will gladly help you fix any issues.
[12:20:57] [Server thread/WARN]: [TabTPS]
[12:20:57] [Server thread/WARN]: [TabTPS]  Join the Paper Community @ https://papermc.io
[12:20:57] [Server thread/WARN]: [TabTPS] ====================================================
[12:20:57] [Server thread/ERROR]: Error occurred while enabling TabTPS v1.3.15 (Is it up to date?)
java.lang.IllegalStateException: Failed to initialize command manager
        at xyz.jpenilla.tabtps.spigot.TabTPSPlugin.onPluginEnable(TabTPSPlugin.java:78) ~[?:?]
        at xyz.jpenilla.tabtps.lib.xyz.jpenilla.jmplib.BasePlugin.onEnable(BasePlugin.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: xyz.jpenilla.tabtps.lib.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
        at xyz.jpenilla.tabtps.lib.cloud.commandframework.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:324) ~[?:?]
        at xyz.jpenilla.tabtps.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:125) ~[?:?]
        at xyz.jpenilla.tabtps.spigot.TabTPSPlugin.setupCommandManager(TabTPSPlugin.java:136) ~[?:?]
        at xyz.jpenilla.tabtps.spigot.TabTPSPlugin.onPluginEnable(TabTPSPlugin.java:76) ~[?:?]
        ... 12 more`

**Comment by jpenilla** [comment]
There's a bug that causes the latest release not to work on spigot. It will work on Paper which you can download here: https://papermc.io/downloads

The dev builds fix this bug but I'd recommend just switching to Paper.
