### ISSUE TITLE
Not displaying on Spigot 1.20.1

### ISSUE THREAD

**Issue by thebue** [jpenilla/TabTPS#64]
This occurs on Spigot 1.20.1, precisely "CraftBukkit version 3815-Spigot-64b565e-9f64f0d (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)" using the 1.3.18 build of TabTPS.

Toggling "tab" and "actionbar" shows no error, but also does not display anything.
Neither does activating "bossbar" but it throws the following exception:

```
[15:43:04] [Server thread/INFO]: PLAYER issued server command: /tabtps toggle actionbar
[15:43:25] [Server thread/INFO]: PLAYER issued server command: /tabtps toggle tab
[15:43:53] [Server thread/INFO]: PLAYER issued server command: /tabtps toggle bossbar
[15:43:53] [Server thread/WARN]: An unexpected error occurred during command execution
java.lang.NoClassDefFoundError: Could not initialize class xyz.jpenilla.tabtps.spigot.util.SpigotReflection$Holder
	at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.spigotReflection(SpigotReflection.java:47) ~[?:?]
	at xyz.jpenilla.tabtps.spigot.service.SpigotTickTimeService.recentTps(SpigotTickTimeService.java:39) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.TPSModule.display(TPSModule.java:48) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.ModuleRenderer.lambda$standardRenderFunction$0(ModuleRenderer.java:54) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.ModuleRenderer.render(ModuleRenderer.java:73) ~[?:?]
	at xyz.jpenilla.tabtps.common.display.task.BossBarDisplayTask.<init>(BossBarDisplayTask.java:57) ~[?:?]
	at xyz.jpenilla.tabtps.common.AbstractUser$StateImpl.lambda$new$2(AbstractUser.java:92) ~[?:?]
	at xyz.jpenilla.tabtps.common.display.DisplayHandler.lambda$startDisplay$0(DisplayHandler.java:66) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at xyz.jpenilla.tabtps.common.display.DisplayHandler.startDisplay(DisplayHandler.java:65) ~[?:?]
	at xyz.jpenilla.tabtps.common.command.commands.ToggleDisplayCommands.toggleBossBar(ToggleDisplayCommands.java:122) ~[?:?]
	at xyz.jpenilla.tabtps.lib.cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[?:?]
	at xyz.jpenilla.tabtps.lib.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[?:?]
	at xyz.jpenilla.tabtps.lib.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:189) ~[?:?]
	at xyz.jpenilla.tabtps.lib.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1922) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Don't know tickTimes field name! [in thread "pool-10-thread-1"]
	at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.tickTimesField(SpigotReflection.java:87) ~[?:?]
	at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.<init>(SpigotReflection.java:67) ~[?:?]
	at xyz.jpenilla.tabtps.spigot.util.SpigotReflection$Holder.<clinit>(SpigotReflection.java:43) ~[?:?]
	at xyz.jpenilla.tabtps.spigot.util.SpigotReflection.spigotReflection(SpigotReflection.java:47) ~[?:?]
	at xyz.jpenilla.tabtps.spigot.service.SpigotTickTimeService.recentTps(SpigotTickTimeService.java:39) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.TPSModule.display(TPSModule.java:48) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.ModuleRenderer.lambda$standardRenderFunction$0(ModuleRenderer.java:54) ~[?:?]
	at xyz.jpenilla.tabtps.common.module.ModuleRenderer.render(ModuleRenderer.java:73) ~[?:?]
	at xyz.jpenilla.tabtps.common.display.task.ActionBarDisplayTask.run(ActionBarDisplayTask.java:55) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
```

Happily providing further info/logs if needed.

Thank you for your great work! 
It really helped me fine tune my little private server I play on with with a couple of friends.

**Comment by jpenilla** [comment]
Thanks for the report, I will look into this when I have time. If you want a solution now, 1.3.18 was tested against [Paper](https://papermc.io/) 1.20.1 and works fine there.

**Comment by tjf801** [comment]
I can confirm I'm getting the same issue.

**Comment by wei1769** [comment]
Is there any new release planned for this fix pr?
Or is there a new hotfix for 1.13.18-spigot?

**Comment by TerdyTheTerd** [comment]
This plugin will not load on my paper 1.20.2 server with the same error posted above.

**Comment by LunarRoze** [comment]
Having this same issue on Spigot 1.21.
